name: Integration Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up
      env:
        CLI_CONFIG: ${{ secrets.cliConfig }}
      run: |
        echo "$CLI_CONFIG" > $HOME/.ask/cli_config
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm link
    - run: npm run integration-test:smapi